CREATE DATABASE s_Cart;
Use s_cart;
CREATE TABLE sCart_details (
    Id INT PRIMARY KEY,
    Title VARCHAR(255),
    Price DECIMAL(10, 2),
    IMAGEURL VARCHAR(255)  
);

ALTER TABLE sCart_details
MODIFY COLUMN Price DECIMAL(10, 2) NOT NULL;

ALTER TABLE sCart_details DROP PRIMARY KEY;
ALTER TABLE sCart_details MODIFY COLUMN Id INT NULL UNIQUE;
ALTER TABLE sCart_details MODIFY COLUMN Id INT AUTO_INCREMENT PRIMARY KEY;








